http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: "/ip"
  user:
    host: localhost
    paths: ["/user", "/user/*"]
  movie:
    host: localhost
    paths: ["/movie", "/movie/*", "/category", "/category/*"]
  actor:
    host: localhost
    paths: ["/actor", "/actor/*"]
serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  userService:
    url: "http://localhost:8001"
  movieService:
    url: "http://localhost:8002"
  actorService:
    url: "http://localhost:8003"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  userPipeline:
    apiEndpoints:
      - user
    policies:
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
  moviePipeline:
    apiEndpoints:
      - movie
    policies:
      - proxy:
          - action:
              serviceEndpoint: movieService
              changeOrigin: true
  actorPipeline:
    apiEndpoints:
      - actor
    policies:
      - proxy:
          - action:
              serviceEndpoint: actorService
              changeOrigin: true
